environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
  access_token:
    secure: ZxcrtxQXwszRYNN6c1ZIagczEqzmQQZeYHY58izcmF0jdq/cptxJvFUoVxDmnoqj
install:
  - ps: New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:Localmachine\My
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
  - echo install
build_script:
  - if "%TARGET%" == "x86_64-pc-windows-msvc" ( cargo doc --no-deps )
  - echo build
test_script:
  # TODO remove this loop when server 2016 lands on appveyor; related to https://github.com/steffengy/schannel-rs/issues/8
  - ps: for($i=1; $i -le 3; $i++) { cmd /c "cargo test 2>&1"; if ($?) { break } }
deploy_script:
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - set deploy=1
  - if not "%APPVEYOR_REPO_NAME%" == "steffengy/schannel-rs" ( set deploy=0 )
  - if not "%APPVEYOR_REPO_BRANCH%" == "master" ( set deploy=0 )
  - if defined APPVEYOR_PULL_REQUEST_NUMBER ( set deploy=0 )
  - if not exist "target\doc" ( set deploy=0 )
  - git config --global credential.helper store
  - git config --global user.name "Appveyor Worker"
  - git config --global user.email "<>"
  - if "%deploy%"=="1" ( move target\doc ..\doc )
  - git checkout gh-pages
  - rd /s /q doc
  - if "%deploy%"=="1" ( move ..\doc doc )
  - git add -A doc
  - 'git commit -am "Appveyor: Autoupdate documentation for %APPVEYOR_REPO_COMMIT%" & ver > nul'
  - 'if "%deploy%"=="1" ( git push origin gh-pages & ver > nul )'
