[package]
name = "schannel"
license = "MIT"
version = "0.0.2"
description = "Schannel bindings for rust, allowing SSL/TLS (e.g. https) without openssl, including hyper integration"
authors = [ "Steffen Butzer <steffen.butzer@outlook.com>" ]
documentation = "http://steffengy.github.io/schannel-rs/doc/schannel/"
repository = "https://github.com/steffengy/schannel-rs"
readme = "README.md"
keywords = ["windows", "schannel", "tls", "https", "hyper"]

[dependencies]
crypt32-sys = "0.2"
kernel32-sys = "0.2"
lazy_static = "0.2"
libc = "0.2"
secur32-sys="0.2"
winapi = "0.2"

[replace]
"winapi:0.2.7" = { git = "https://github.com/sfackler/winapi-rs" }