[package]

name = "schannel"
license = "MIT"
version = "0.0.1"
description = "Schannel bindings for rust, allowing SSL/TLS (e.g. https) without openssl, including hyper integration"
authors = [ "Steffen Butzer <steffen.butzer@outlook.com>" ]
documentation = "http://steffengy.github.io/schannel-rs/doc/schannel/"
repository = "https://github.com/steffengy/schannel-rs"
readme = "README.md"
keywords = ["windows", "schannel", "tls", "https", "hyper"]

[lib]
name = "schannel"
path = "src/lib.rs"
test = false
bench = false

[dependencies]
rustc-serialize = "0.3"
hyper = { version = "0.7.2", optional = true, default-features = false }
log = "0.3"
winapi = "0.2"
secur32-sys="0.2"
crypt32-sys="0.2"

[dev-dependencies]
env_logger = "*"

[features]
default = ["hyper"]
